// lib/domain/entities/pronunciation_pair.dart

/// Holds both pronunciation representations for a single Greek word.
///
/// Modern Greek: how the word sounds today — played via TtsService.
/// Koine: academic phonetic reconstruction — display only, never audio.
///
/// See project handoff doc, dual-pronunciation system:
///   "Do NOT use TTS for Koine. Instead generate or store phonetic
///    approximation. This is DISPLAY ONLY, not audio."
class PronunciationPair {
  /// Romanized Modern Greek form (e.g. "logos"). Used as the label under
  /// the TTS play button so the user knows what they're hearing.
  final String modernGreek;

  /// Koine reconstructed phonetic form (e.g. "log-os"). Erasmian-style,
  /// deterministically generated by KoinePhoneticService. Display only.
  final String koineGreek;

  /// Optional fallback if neither system produces a result (rare).
  final String? phoneticFallback;

  const PronunciationPair({
    required this.modernGreek,
    required this.koineGreek,
    this.phoneticFallback,
  });

  /// The best available Modern Greek display string.
  String get modernDisplay =>
      modernGreek.isNotEmpty ? modernGreek : (phoneticFallback ?? '');

  /// The best available Koine display string.
  String get koineDisplay =>
      koineGreek.isNotEmpty ? koineGreek : (phoneticFallback ?? '');
}